chore: Update MSRV to 1.88
When compiling for Windows, the homedir crate uses features that have
been stabilized on 1.88, so let the MSRV match that. Also run the source
code checks on Windows, so that those things will be caught by it in
the future.

This is the error:

    error[E0658]: `let` expressions in this position are unstable
       --> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\homedir-0.3.5\src\windows.rs:203:16
        |
    203 |             if let Err(e) = GetTokenInformation(token_handle, TokenUser, None, 0, &mut buffer_size)
        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

    For more information about this error, try `rustc --explain E0658`.
    error: could not compile `homedir` (lib) due to 1 previous error